# Copyright (c) 2026, Adel Noureddine.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the
# GNU Lesser General Public License v3.0 (LGPL-3.0-only)
# which accompanies this distribution, and is available at
# https://www.gnu.org/licenses/lgpl-3.0.en.html
#
# Author : Adel Noureddine

# Joular Code - Java: Configuration
# 
# Power source type from Joular Core
# Options:
#   csv (read power from CSV file)
#   http (read from HTTP endpoint/websockets)
#   ringbuffer (read from shared memory ring buffer, IPC)
power-source-type=ringbuffer

# Path to Joular Core CSV file (if power-source-type is csv)
joular-core-csv-path=C:\\joularcore\\joularcore-data.csv

# Joular Core API URL (if power-source-type is http)
joular-core-http-url=http://localhost:8080/data

# Path to ring buffer (if power-source-type is ringbuffer)
# Joular Core default on Linux: /dev/shm/joularcorering
# Joular Core default on macOS: /tmp/joularcorering
# Joular Core default on Windows: Local\\JoularCoreRing
joular-core-ringbuffer-path=Local\\JoularCoreRing

# The sample rate (milliseconds) for the agent to monitor methods usage
# by calling the JVM stack
# Default is 10 ms making a good balance between accurancy and efficiency
# Higher count means less accurate energy data
# Lower count means higher overhead of the agent
stack-monitoring-sample-rate=10

# Output folder for results
results-path=joular-code-java-results

# Prefix to filter monitoring of methods
# If set, only methods where their full canonical name (package.class.method) starting with this prefix will be monitored
# If not set, the top method of the stack is monitored regardless of package
# Example: methods-filtering-prefix=Package to filter energy for all methods whose full name start with Package
# Note that Joular Code Java will always generate energy for all non-filtered method in a separate file
# So you can safely keep this empty if you don't want to filter methods
# You can add multiple identifiers names separated by a comma, ordered by priority
# Joular Code Java will monitor and filter methods for all these packages
# Example: methods-filtering-prefix=Package,Package2,Package3
methods-filtering-prefix=Package